### ISSUE TITLE
Error on Monterrey

### ISSUE THREAD

**Issue by krolingo** [aaburger85/MerakiUebersichtColorized#3]
Error: Traceback (most recent call last): File "/Users/me/Library/Application Support/Übersicht/widgets/./AirportData/WifiLine.Airport.py", line 59, in <module> bssiddict = dict((x, y) for x, y in tuplebssid) File "/Users/me/Library/Application Support/Übersicht/widgets/./AirportData/WifiLine.Airport.py", line 59, in <genexpr> bssiddict = dict((x, y) for x, y in tuplebssid) ValueError: not enough values to unpack (expected 2, got 1)
wrapError — client.js:1:903834
(anonymous function) — client.js:1:904158
(anonymous function) — client.js:1:871964
(anonymous function) — client.js:1:869472
(anonymous function) — client.js:1:76025
(anonymous function) — client.js:1:873415
redraw — client.js:1:888047
(anonymous function) — client.js:1:886595
(anonymous function) — client.js:1:871964
(anonymous function) — client.js:1:869472
(anonymous function) — client.js:1:76025
(anonymous function) — client.js:1:873415
http://127.0.0.1:41416/run/

Python 3.9.5 (default, May  4 2021, 03:36:27) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin

**Comment by mburger89** [comment]
This is fixed in this #4 just waiting for review and merge
